### ISSUE TITLE
Update colour palette

### ISSUE THREAD

**Issue by kcema** [kcema/home#11]
The entire site is black and white. The text at the top, with the white outlined in black on a black and white background is difficult to see. 

Find a new palette, and update the CSS or inline HTML as needed

**Comment by j5awry** [comment]
Short meeting on Tuesday, Oct. 4th, took a quick look at palettes. This one is pretty good?

http://www.color-hex.com/color-palette/3714

**Comment by j5awry** [comment]
this one might be better. similar, but a little more vibrant?

http://paletton.com/#uid=63k0s0ktJjAlsr6BfpeFffSM99K

**Comment by j5awry** [comment]
<img width="1300" alt="screen shot 2016-10-08 at 4 52 43 pm" src="https://cloud.githubusercontent.com/assets/8875872/19216181/da59930a-8d77-11e6-9c3f-b1ffe3a6a1fd.png">

**Comment by j5awry** [comment]
closing old issue. updated in 2016
